name: Oil Market Scraping Scheduler

on:

  schedule:
    - cron: "0 12 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:

  scrape:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt

      - name: Reset database
        run: |
          python -c "from database.db import resetDatabase; resetDatabase()"

      - name: Run news scraper
        run: |
          python -m scrapping.news_scraper

      - name: Run oil price scraper
        run: |
          python -m scrapping.oil_prices_scraper

      - name: Run sentiment analysis
        run: |
          python -m analytics.sentiment_analysis
      
      - name: Run top keywords analysis
        run: |
          python -m analytics.top_k_analysis

      - name: Run oil prices analysis
        run: |
          python -m analytics.oil_prices_analysis

      - name: Run correlation analysis
        run: |
          python -m analytics.correlation_analysis

      - name: Commit updated data
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add data/

          git commit -m "Automated scraping update" || echo "No changes to commit"

          git push